### ISSUE TITLE
Help - please :)

### ISSUE THREAD

**Issue by johnmcavoy** [mohameosam/open_excel#4]
Hi there,

Newbie question.  Im trying to use the open_excel module like the read_csv module. I have had some good success using this module in building network configurations but would prefer to use open_excel as all my variable data sources would be contained in one place as opposed to many multiple files, which I imagine was the original intent in making it. 

Unfortunately, I lack the knowledge to convert the output like I have done with the read_csv and used it in loops through my configurations. Any tips or advice on how to do this would be greatly received.

The example below is for my csv and playbook that calls the csv. 

-------
tenant,description,state
prod,prod_tenant,present
-------

-------
  - name: "Reading user information"
    read_csv:
      path: ../csv/tenants.csv
    register: tenants

  - name: "Add a new tenant"
    aci_tenant:
      tenant: "{{ tenants.tenant }}"
      description: "{{ tenants.description }}"
      state: "{{ tenants.state }}"
    delegate_to: localhost

    loop: "{{ tenants.list }}"
    loop_control:
      loop_var: tenants

Thanks

John

**Comment by mohameosam** [comment]
If your intent is to read multiple cells from a single sheet in an excel file, then you should specify the file name, sheet name, and the "read range". The "read range" is a dictionary variable.

For example, if your data in a file tenants.xlsx under "sheet1" and in the cells A2 to A100. The following Ansible code snippet should return a list of dictionaries with all the read values in the variable "my_tenants":

```
var:
  read_range:
    start_row: 2
    end_row: 100
    start_col: 1
    end_col: 1

tasks:
  - name: Read my excel sheet
    register: my_tenants
    open_excel:
      op: "r"
      index_by_name: False
      read_range: "{{ read_range }}"
      sec: "tenants.xlsx"
      sheet_name: "sheet1"
```
