### ISSUE TITLE
Write to excel using variables

### ISSUE THREAD

**Issue by johnmcavoy** [mohameosam/open_excel#5]
Hi there, 

I would like to know if its possible to insert variables into the update matrix

op: "w"
          updates_matrix: "{{ [{'cell_row': 4, 'cell_col': 3, 'cell_value': 'Sacramento Data Center'}, {'cell_row': 4, 'cell_col': 4, 'cell_value': 'SN55566677'}] }}"

Basically I would like to able to insert {{ variable }} into the cell value fields and am not sure how to or if its even possible?

Thanks

**Comment by mohameosam** [comment]
Do you mean an Ansible variable or excel variable. Are you taking specifically about writing lists? Ansible variables are perfectly fine and possible, excel variables are not supported.

In an Ansible variable case with the example you have written above, your updates_matrix would be a dictionary that can be assigned a value directly or constructed from other variables. That would be a pure Ansible coding. So, it can be something like:

```
vars:
  my_cell_row_var: 4
  my_cell_col_var: 3
  my_cell_value_var: 'Sacramento Data Center'

tasks:
  - set_fact:
      updates_matrix:
        cell_row: "{{ my_cell_row_var }}"
        cell_col: "{{ my_cell_col_var }}"
        cell_value: "{{ my_cell_value_var }}" 

```

For Ansible lists, these are not yet supported. I have been getting requests to do that to avoid using loops in Ansible for performance reasons, I may add that sometime soon.
